" note: this is an autogenerated file

" MAPPINGS (origin: nvim/lua/fmajor/remap.lua)

let g:mapleader = " "
let g:maplocalleader = "\\"


" moving the visually selected area 
vnoremap J :m '>+1<CR>gv=gv
vnoremap K :m '<-2<CR>gv=gv

" append the next line without moving the cursor
nnoremap J mzJ`z
" keep the cursor in the middle of the screen
nnoremap <C-d> <C-d>zz
nnoremap <C-u> <C-u>zz
nnoremap n nzzzv
nnoremap N Nzzzv

" paste without overwriting the register
xnoremap <leader>p "_dP
" yank to the system clipboard
nnoremap <leader>y "+y
vnoremap <leader>y "+y
nnoremap <leader>Y "+Y

" delete to the void register
nnoremap <leader>d "_d
vnoremap <leader>d "_d
nnoremap <leader>x "_x
vnoremap <leader>x "_x
nnoremap <leader>D "_D
vnoremap <leader>D "_D

" remap splits to mimic tmux bindings
nnoremap <C-w>\\ <C-w>v
nnoremap <C-w>- <C-w>s

" remove Q
nnoremap Q <nop>


" SETS (origin: nvim/lua/fmajor/set.lua)
set guicursor=""

set nu
set relativenumber

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

set smartindent

set nowrap

set noswapfile
set nobackup
set undodir=os.getenv("HOME") .. "/.vim/undodir"
set undofile

set nohlsearch
set incsearch



set scrolloff=8
set signcolumn="yes"


set updatetime=50

set colorcolumn="80"


